// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package server_ping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestEnvelope struct {
	ServiceMethod        string    `protobuf:"bytes,1,opt,name=serviceMethod,proto3" json:"serviceMethod,omitempty"`
	Seq                  uint64    `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Headers              []*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RequestEnvelope) Reset()         { *m = RequestEnvelope{} }
func (m *RequestEnvelope) String() string { return proto.CompactTextString(m) }
func (*RequestEnvelope) ProtoMessage()    {}
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{1}
}

func (m *RequestEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEnvelope.Unmarshal(m, b)
}
func (m *RequestEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEnvelope.Marshal(b, m, deterministic)
}
func (m *RequestEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEnvelope.Merge(m, src)
}
func (m *RequestEnvelope) XXX_Size() int {
	return xxx_messageInfo_RequestEnvelope.Size(m)
}
func (m *RequestEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEnvelope proto.InternalMessageInfo

func (m *RequestEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *RequestEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RequestEnvelope) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type ResponseEnvelope struct {
	ServiceMethod        string   `protobuf:"bytes,1,opt,name=serviceMethod,proto3" json:"serviceMethod,omitempty"`
	Seq                  uint64   `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	HttpCode             int64    `protobuf:"varint,4,opt,name=httpCode,proto3" json:"httpCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseEnvelope) Reset()         { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()    {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{2}
}

func (m *ResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEnvelope.Unmarshal(m, b)
}
func (m *ResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *ResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEnvelope.Merge(m, src)
}
func (m *ResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_ResponseEnvelope.Size(m)
}
func (m *ResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEnvelope proto.InternalMessageInfo

func (m *ResponseEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *ResponseEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ResponseEnvelope) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponseEnvelope) GetHttpCode() int64 {
	if m != nil {
		return m.HttpCode
	}
	return 0
}

type PingRequest struct {
	Request              *RequestEnvelope `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{3}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetRequest() *RequestEnvelope {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ServiceStatus struct {
	DBStats              *DBStats `protobuf:"bytes,1,opt,name=DBStats,proto3" json:"DBStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{4}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetDBStats() *DBStats {
	if m != nil {
		return m.DBStats
	}
	return nil
}

type DBStats struct {
	MaxOpenConnections   int64    `protobuf:"varint,1,opt,name=maxOpenConnections,proto3" json:"maxOpenConnections,omitempty"`
	OpenConnections      int64    `protobuf:"varint,2,opt,name=openConnections,proto3" json:"openConnections,omitempty"`
	InUse                int64    `protobuf:"varint,3,opt,name=inUse,proto3" json:"inUse,omitempty"`
	Idle                 int64    `protobuf:"varint,4,opt,name=idle,proto3" json:"idle,omitempty"`
	WaitCount            int64    `protobuf:"varint,5,opt,name=waitCount,proto3" json:"waitCount,omitempty"`
	WaitDuration         int64    `protobuf:"varint,6,opt,name=waitDuration,proto3" json:"waitDuration,omitempty"`
	MaxIdleClosed        int64    `protobuf:"varint,7,opt,name=maxIdleClosed,proto3" json:"maxIdleClosed,omitempty"`
	MaxLifetimeClosed    int64    `protobuf:"varint,8,opt,name=maxLifetimeClosed,proto3" json:"maxLifetimeClosed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBStats) Reset()         { *m = DBStats{} }
func (m *DBStats) String() string { return proto.CompactTextString(m) }
func (*DBStats) ProtoMessage()    {}
func (*DBStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{5}
}

func (m *DBStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBStats.Unmarshal(m, b)
}
func (m *DBStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBStats.Marshal(b, m, deterministic)
}
func (m *DBStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBStats.Merge(m, src)
}
func (m *DBStats) XXX_Size() int {
	return xxx_messageInfo_DBStats.Size(m)
}
func (m *DBStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DBStats.DiscardUnknown(m)
}

var xxx_messageInfo_DBStats proto.InternalMessageInfo

func (m *DBStats) GetMaxOpenConnections() int64 {
	if m != nil {
		return m.MaxOpenConnections
	}
	return 0
}

func (m *DBStats) GetOpenConnections() int64 {
	if m != nil {
		return m.OpenConnections
	}
	return 0
}

func (m *DBStats) GetInUse() int64 {
	if m != nil {
		return m.InUse
	}
	return 0
}

func (m *DBStats) GetIdle() int64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *DBStats) GetWaitCount() int64 {
	if m != nil {
		return m.WaitCount
	}
	return 0
}

func (m *DBStats) GetWaitDuration() int64 {
	if m != nil {
		return m.WaitDuration
	}
	return 0
}

func (m *DBStats) GetMaxIdleClosed() int64 {
	if m != nil {
		return m.MaxIdleClosed
	}
	return 0
}

func (m *DBStats) GetMaxLifetimeClosed() int64 {
	if m != nil {
		return m.MaxLifetimeClosed
	}
	return 0
}

type PingResponse struct {
	Response             *ResponseEnvelope `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status               *ServiceStatus    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{6}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetResponse() *ResponseEnvelope {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PingResponse) GetStatus() *ServiceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "server.ping.Header")
	proto.RegisterType((*RequestEnvelope)(nil), "server.ping.RequestEnvelope")
	proto.RegisterType((*ResponseEnvelope)(nil), "server.ping.ResponseEnvelope")
	proto.RegisterType((*PingRequest)(nil), "server.ping.PingRequest")
	proto.RegisterType((*ServiceStatus)(nil), "server.ping.ServiceStatus")
	proto.RegisterType((*DBStats)(nil), "server.ping.DBStats")
	proto.RegisterType((*PingResponse)(nil), "server.ping.PingResponse")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor_6d51d96c3ad891f5) }

var fileDescriptor_6d51d96c3ad891f5 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0x75, 0x12, 0xa7, 0xe3, 0x56, 0x2d, 0x43, 0x0e, 0x4b, 0x54, 0xa4, 0xc8, 0xe2, 0x90,
	0x03, 0x58, 0xc8, 0x48, 0x48, 0x1c, 0x10, 0x12, 0x69, 0x25, 0x90, 0x40, 0xa0, 0xad, 0x38, 0x23,
	0x53, 0x0f, 0x89, 0x85, 0xbd, 0xeb, 0xee, 0xae, 0x43, 0x90, 0xf8, 0x0f, 0x3e, 0x80, 0x1f, 0x45,
	0xbb, 0x6b, 0x87, 0x3a, 0x94, 0x13, 0x27, 0xcf, 0xbc, 0x79, 0x3b, 0x33, 0xfb, 0xde, 0x1a, 0xa0,
	0x2e, 0xc4, 0x2a, 0xa9, 0x95, 0x34, 0x12, 0x23, 0x4d, 0x6a, 0x43, 0x2a, 0xb1, 0x50, 0xfc, 0x04,
	0xc6, 0xaf, 0x29, 0xcb, 0x49, 0xe1, 0x29, 0x04, 0x5f, 0xe9, 0x3b, 0x1b, 0xcc, 0x07, 0x8b, 0x43,
	0x6e, 0x43, 0x9c, 0xc2, 0x68, 0x93, 0x95, 0x0d, 0xb1, 0x03, 0x87, 0xf9, 0x24, 0xde, 0xc2, 0x09,
	0xa7, 0xeb, 0x86, 0xb4, 0xb9, 0x10, 0x1b, 0x2a, 0x65, 0x4d, 0xf8, 0x10, 0x8e, 0x6d, 0xcf, 0xe2,
	0x8a, 0xde, 0x91, 0x59, 0xcb, 0xbc, 0x6d, 0xd2, 0x07, 0xed, 0x00, 0x4d, 0xd7, 0xae, 0xd9, 0x98,
	0xdb, 0x10, 0x1f, 0x43, 0xb8, 0x76, 0xc3, 0x35, 0x0b, 0xe6, 0xc1, 0x22, 0x4a, 0xef, 0x25, 0x37,
	0x76, 0x4b, 0xfc, 0x62, 0xbc, 0xe3, 0xc4, 0x3f, 0xe0, 0x94, 0x93, 0xae, 0xa5, 0xd0, 0xf4, 0xdf,
	0xa3, 0xa7, 0x30, 0x22, 0xa5, 0xa4, 0x62, 0x81, 0xbf, 0x9b, 0x4b, 0x70, 0x06, 0x93, 0xb5, 0x31,
	0xf5, 0x52, 0xe6, 0xc4, 0x86, 0xf3, 0xc1, 0x22, 0xe0, 0xbb, 0x3c, 0xfe, 0x04, 0xd1, 0x87, 0x42,
	0xac, 0xda, 0xbb, 0xe3, 0x33, 0x08, 0x95, 0x0f, 0xdd, 0xc8, 0x28, 0x3d, 0xeb, 0xed, 0xbe, 0x27,
	0x11, 0xef, 0xc8, 0xc8, 0x20, 0xac, 0x48, 0xeb, 0x6c, 0xd5, 0xc9, 0xda, 0xa5, 0xf1, 0x4b, 0x38,
	0xbe, 0xf4, 0x5b, 0x5f, 0x9a, 0xcc, 0x34, 0x1a, 0x13, 0x08, 0xcf, 0x5f, 0xd9, 0x58, 0xb7, 0x23,
	0xa6, 0xbd, 0x11, 0x6d, 0x8d, 0x77, 0xa4, 0xf8, 0xd7, 0xc1, 0xee, 0x00, 0x26, 0x80, 0x55, 0xb6,
	0x7d, 0x5f, 0x93, 0x58, 0x4a, 0x21, 0xe8, 0xca, 0x14, 0x52, 0xf8, 0x36, 0x01, 0xbf, 0xa5, 0x82,
	0x0b, 0x38, 0x91, 0x7b, 0xe4, 0x03, 0x47, 0xde, 0x87, 0xad, 0x72, 0x85, 0xf8, 0xa8, 0xc9, 0x29,
	0x17, 0x70, 0x9f, 0x20, 0xc2, 0xb0, 0xc8, 0xcb, 0x4e, 0x35, 0x17, 0xe3, 0x19, 0x1c, 0x7e, 0xcb,
	0x0a, 0xb3, 0x94, 0x8d, 0x30, 0x6c, 0xe4, 0x0a, 0x7f, 0x00, 0x8c, 0xe1, 0xc8, 0x26, 0xe7, 0x8d,
	0xca, 0x6c, 0x63, 0x36, 0x76, 0x84, 0x1e, 0x66, 0xdd, 0xad, 0xb2, 0xed, 0x9b, 0xbc, 0xa4, 0x65,
	0x29, 0x35, 0xe5, 0x2c, 0x74, 0xa4, 0x3e, 0x88, 0x8f, 0xe0, 0x6e, 0x95, 0x6d, 0xdf, 0x16, 0x5f,
	0xc8, 0x14, 0x55, 0xc7, 0x9c, 0x38, 0xe6, 0xdf, 0x85, 0xf8, 0xe7, 0x00, 0x8e, 0xbc, 0x91, 0xfe,
	0x29, 0xe1, 0x73, 0x98, 0xa8, 0x36, 0x6e, 0x75, 0x7e, 0xb0, 0x67, 0x65, 0xff, 0xcd, 0xf1, 0x1d,
	0xfd, 0xdf, 0x66, 0x62, 0x0a, 0x63, 0xed, 0x5c, 0x74, 0x32, 0x45, 0xe9, 0xac, 0xd7, 0xb2, 0xe7,
	0x33, 0x6f, 0x99, 0xe9, 0x05, 0x0c, 0xed, 0x62, 0xf8, 0xa2, 0xfd, 0xb2, 0xde, 0x99, 0x1b, 0x8f,
	0x6f, 0x76, 0xff, 0x96, 0x8a, 0x5f, 0x29, 0xbe, 0xf3, 0x79, 0xec, 0x7e, 0xf3, 0xa7, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xfd, 0xf8, 0x0c, 0x79, 0xf4, 0x03, 0x00, 0x00,
}
