// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: ping.proto

package server_ping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Ping service

type PingService interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error)
}

type pingService struct {
	c    client.Client
	name string
}

func NewPingService(name string, c client.Client) PingService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "server.ping"
	}
	return &pingService{
		c:    c,
		name: name,
	}
}

func (c *pingService) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error) {
	req := c.c.NewRequest(c.name, "Ping.Ping", in)
	out := new(PingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingHandler interface {
	Ping(context.Context, *PingRequest, *PingResponse) error
}

func RegisterPingHandler(s server.Server, hdlr PingHandler, opts ...server.HandlerOption) error {
	type ping interface {
		Ping(ctx context.Context, in *PingRequest, out *PingResponse) error
	}
	type Ping struct {
		ping
	}
	h := &pingHandler{hdlr}
	return s.Handle(s.NewHandler(&Ping{h}, opts...))
}

type pingHandler struct {
	PingHandler
}

func (h *pingHandler) Ping(ctx context.Context, in *PingRequest, out *PingResponse) error {
	return h.PingHandler.Ping(ctx, in, out)
}
