// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package server_ping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestEnvelope struct {
	ServiceMethod        string    `protobuf:"bytes,1,opt,name=serviceMethod,proto3" json:"serviceMethod,omitempty"`
	Seq                  uint64    `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Headers              []*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RequestEnvelope) Reset()         { *m = RequestEnvelope{} }
func (m *RequestEnvelope) String() string { return proto.CompactTextString(m) }
func (*RequestEnvelope) ProtoMessage()    {}
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{1}
}

func (m *RequestEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEnvelope.Unmarshal(m, b)
}
func (m *RequestEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEnvelope.Marshal(b, m, deterministic)
}
func (m *RequestEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEnvelope.Merge(m, src)
}
func (m *RequestEnvelope) XXX_Size() int {
	return xxx_messageInfo_RequestEnvelope.Size(m)
}
func (m *RequestEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEnvelope proto.InternalMessageInfo

func (m *RequestEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *RequestEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RequestEnvelope) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type ResponseEnvelope struct {
	ServiceMethod        string   `protobuf:"bytes,1,opt,name=serviceMethod,proto3" json:"serviceMethod,omitempty"`
	Seq                  uint64   `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	HttpCode             int64    `protobuf:"varint,4,opt,name=httpCode,proto3" json:"httpCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseEnvelope) Reset()         { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()    {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{2}
}

func (m *ResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEnvelope.Unmarshal(m, b)
}
func (m *ResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *ResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEnvelope.Merge(m, src)
}
func (m *ResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_ResponseEnvelope.Size(m)
}
func (m *ResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEnvelope proto.InternalMessageInfo

func (m *ResponseEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *ResponseEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ResponseEnvelope) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponseEnvelope) GetHttpCode() int64 {
	if m != nil {
		return m.HttpCode
	}
	return 0
}

type PingRequest struct {
	Request              *RequestEnvelope `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{3}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetRequest() *RequestEnvelope {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingResponse struct {
	Response             *ResponseEnvelope `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{4}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetResponse() *ResponseEnvelope {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "server.ping.Header")
	proto.RegisterType((*RequestEnvelope)(nil), "server.ping.RequestEnvelope")
	proto.RegisterType((*ResponseEnvelope)(nil), "server.ping.ResponseEnvelope")
	proto.RegisterType((*PingRequest)(nil), "server.ping.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "server.ping.PingResponse")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor_6d51d96c3ad891f5) }

var fileDescriptor_6d51d96c3ad891f5 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x69, 0x93, 0x3a, 0x51, 0x2c, 0x6b, 0x0f, 0x6b, 0x51, 0x08, 0x8b, 0x87, 0x5c,
	0x0c, 0x12, 0x41, 0xf0, 0xe0, 0x49, 0x0a, 0x5e, 0x04, 0xd9, 0x3f, 0x20, 0xb1, 0x19, 0x92, 0x60,
	0xcd, 0xa6, 0xbb, 0x69, 0x50, 0xf0, 0xc7, 0xcb, 0xee, 0x26, 0xa5, 0x29, 0x7a, 0xf2, 0x94, 0x79,
	0x93, 0xe1, 0x7d, 0xf3, 0x86, 0x05, 0xa8, 0xcb, 0x2a, 0x8f, 0x6b, 0x29, 0x1a, 0x41, 0x02, 0x85,
	0xb2, 0x45, 0x19, 0xeb, 0x16, 0xbb, 0x01, 0xef, 0x09, 0xd3, 0x0c, 0x25, 0x99, 0x82, 0xfb, 0x8e,
	0x5f, 0xd4, 0x09, 0x9d, 0xe8, 0x88, 0xeb, 0x92, 0xcc, 0x60, 0xdc, 0xa6, 0xab, 0x0d, 0xd2, 0x43,
	0xd3, 0xb3, 0x82, 0x7d, 0xc2, 0x29, 0xc7, 0xf5, 0x06, 0x55, 0xb3, 0xa8, 0x5a, 0x5c, 0x89, 0x1a,
	0xc9, 0x15, 0x9c, 0x68, 0xcf, 0x72, 0x89, 0xcf, 0xd8, 0x14, 0x22, 0xeb, 0x4c, 0x86, 0x4d, 0x0d,
	0x50, 0xb8, 0x36, 0x66, 0x1e, 0xd7, 0x25, 0xb9, 0x06, 0xbf, 0x30, 0x70, 0x45, 0xdd, 0xd0, 0x8d,
	0x82, 0xe4, 0x2c, 0xde, 0xd9, 0x2d, 0xb6, 0x8b, 0xf1, 0x7e, 0x86, 0x7d, 0xc3, 0x94, 0xa3, 0xaa,
	0x45, 0xa5, 0xf0, 0xdf, 0xe8, 0x19, 0x8c, 0x51, 0x4a, 0x21, 0xa9, 0x6b, 0xb3, 0x19, 0x41, 0xe6,
	0x30, 0x29, 0x9a, 0xa6, 0x7e, 0x14, 0x19, 0xd2, 0x51, 0xe8, 0x44, 0x2e, 0xdf, 0x6a, 0xf6, 0x0a,
	0xc1, 0x4b, 0x59, 0xe5, 0x5d, 0x76, 0x72, 0x07, 0xbe, 0xb4, 0xa5, 0x41, 0x06, 0xc9, 0xc5, 0x60,
	0xf7, 0xbd, 0x13, 0xf1, 0x7e, 0x98, 0x50, 0xf0, 0x3f, 0x50, 0xa9, 0x34, 0xef, 0xcf, 0xda, 0x4b,
	0xb6, 0x84, 0x63, 0x0b, 0xb0, 0x11, 0xc9, 0x3d, 0x4c, 0x64, 0x57, 0x77, 0x88, 0xcb, 0x3d, 0xc4,
	0xf0, 0x16, 0x7c, 0x3b, 0xfe, 0x37, 0x24, 0x59, 0xc0, 0x48, 0x43, 0xc8, 0x43, 0xf7, 0xa5, 0x03,
	0xcb, 0x9d, 0x80, 0xf3, 0xf3, 0x5f, 0xfe, 0x58, 0x7b, 0x76, 0xf0, 0xe6, 0x99, 0xa7, 0x74, 0xfb,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xaa, 0x9f, 0x74, 0x58, 0x02, 0x00, 0x00,
}
